### ISSUE TITLE
Which tools used to draw such a variety of elegant and decent Figures?

### ISSUE THREAD

**Issue by dragen1860** [stanfordnlp/mac-network#1]
Hi, Thanks for your insightful work.
 I want to know **which tools** you used to draw the figures in your BLOGPOST and paper. There all look so attracting & vivid!

**Comment by dorarad** [comment]
Hi, thank you for the interest! For the attention visualizations i used a python script located in this repo called visualization.py. For other plots I used either standard matplotlib for some and for others (specifically for the error analysis pie charts) i used excel :)

**Comment by hughperkins** [comment]
The cell diagrams are particularly nice. Good information :)
