### ISSUE TITLE
Difference between all_val_data.json and val_all_questions.json

### ISSUE THREAD

**Issue by Moymix** [stanfordnlp/mac-network#10]
There is a file called all_val_data.json (436.4MB) in https://nlp.stanford.edu/data/gqa/data.zip and a similar file called val_all_questions.json (1.7G) in https://nlp.stanford.edu/data/gqa/questions.zip.
So, which one is the validation set?

**Comment by dorarad** [comment]
Hi, both of them are the same validation set - the only difference is that questions.zip is the official version which contains all the information about each of the validation questions whereas to train MAC over GQA I made a lighter version of the data only with the information MAC needs, which is at data.zip (e.g. MAC doesn't need the functional programs). Hope it resolves the confusion!

**Comment by dorarad** [comment]
I also added a comment about it in the readme
