### ISSUE TITLE
ValueError while training on data1.2

### ISSUE THREAD

**Issue by limoneren** [stanfordnlp/mac-network#20]
I followed the instructions on the [readme.md](https://github.com/stanfordnlp/mac-network/blob/gqa/readme.md) and the training part worked with no error with data.zip before.

However, when I clone the current version of the gqa branch and followed the instructions on the same md from the beginning(downloading everything again and merging), I am getting the following error in the training part just after the first epoch:

`ValueError: Index (148690) out of range (0-108076)`

Full stack trace after the first epoch is as follows:

```bash
eb  1, 78 (10000 / 10000), t = 0.32 (0.00+0.23), lr 0.0003, l = 1.9574, a = 0.5469, avL = 1.9961, avA = 0.5434, g = -1.0000, emL = 2.0224, emA = 0.5367; gqaExTraceback (most recent call last):
  File "main.py", line 848, in <module>
    main()
  File "main.py", line 710, in main
    evalRes = runEvaluation(sess, model, data["main"], dataOps, epoch, getPreds = getPreds, prevRes = evalRes)
  File "main.py", line 251, in runEvaluation
    minLoss = prevRes["val"]["minLoss"] if prevRes else float("inf"))
  File "main.py", line 571, in runEpoch
    imagesBatch = loadImageBatch(data["images"], batch)
  File "main.py", line 363, in loadImageBatch
    imageBatch[i, 0:numObjects] = toFile(imageId)["features"][imageId["idx"], 0:numObjects]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 457, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 477, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (148690) out of range (0-108076)
```

**Comment by dorarad** [comment]
oh sorry that's right the test-dev question rely on images in a different h5 file than train/val so have to change it accordingly. Alright for now will revert back to val to make it work in the meantime and then will make the needed change to make it work for test-dev.

**Comment by dorarad** [comment]
Alright for now I updated the `preprocess.py` file to read back val instead of test-dev so this works without errors with val for now.

In addition I made an update to `https://github.com/stanfordnlp/mac-network/blob/gqa/merge.py` (should work but haven't verified yet). If you're interested in running on test-dev (as I recommend!) please try to run `merge.py` again following the instructions on the readme: `python merge.py --name objects` and `python merge.py --name objects`, and afterwards you can run on test-dev either by passing `--test` to the model or by changing the value here: `https://github.com/stanfordnlp/mac-network/blob/gqa/preprocess.py#L829` from `val` to `testdev.` 

After I verify that this works smoothly for people will make a new commit with the `val` -> `testdev` change.

**Comment by limoneren** [comment]
I re-run the latest version of merge.py as you suggested, and changed the line 829 of preprocess.py as `dataset["val"] = self.readTier("testdev" + suffix, train = trainOnVal)`, but again at the end of the first epoch, it failed.

```bash
Traceback (most recent call last):
  File "main.py", line 848, in <module>
    main()
  File "main.py", line 710, in main
    evalRes = runEvaluation(sess, model, data["main"], dataOps, epoch, getPreds = getPreds, prevRes = evalRes)
  File "main.py", line 251, in runEvaluation
    minLoss = prevRes["val"]["minLoss"] if prevRes else float("inf"))
  File "main.py", line 571, in runEpoch
    imagesBatch = loadImageBatch(data["images"], batch)
  File "main.py", line 363, in loadImageBatch
    imageBatch[i, 0:numObjects] = toFile(imageId)["features"][imageId["idx"], 0:numObjects]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 457, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/ec2-user/conda/envs/tf_gpu/lib/python3.6/site-packages/h5py/_hl/selections.py", line 477, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (148690) out of range (0-148689)
```

**Comment by dorarad** [comment]
sorry about that will check and get back to you!

**Comment by dorarad** [comment]
alright I made a mistake in the update for `merge.py`. Fixed it now. You can either wait for me to verify that or try the new version, hopefully it will work this time!

**Comment by limoneren** [comment]
I tried it and got the following error after the first epoch. 
```bash
ValueError: Index (148887) out of range (0-148854)
```
If it helps, here is what I did:
- Re-run the merge.py with the updated version.
- preprocess.py is the same with here, but the line 829 is changed to:
`dataset["val"] = self.readTier("testdev" + suffix, train = trainOnVal)`
- Run `python main.py --expName "gqaExperiment" --train --testedNum 10000 --epochs 25 --netLength 4 @configs/gqa/gqa.txt`

**Comment by dorarad** [comment]
sorry a lot for that and especially for keep having issues with that. I will test it tomorrow and get back to you.

**Comment by dorarad** [comment]
oh ok I think I found the error sorry pushing now a new update to merge but I do want to validate it myself before asking you to rerun again. Will do so by tomorrow and update you if it worked / with the solution!

**Comment by dorarad** [comment]
(sorry for the delay haven't got to test it yet will update as soon as I do)

**Comment by dorarad** [comment]
alright tested not it works for me, please let me know if it works for you as well!

**Comment by dorarad** [comment]
alright tested now it works for me, please let me know if it works for you as well!

**Comment by dorarad** [comment]
Hey, please let me know if it worked for you or if there's anything else i can help with! :)

**Comment by limoneren** [comment]
Thank you! I'm testing it and It's currently on epoch 17. It looks like it works well. :) Another question, is there any possibility that the challenge deadline may be postponed a little?

**Comment by dorarad** [comment]
Awesome! :) Yea actually I do consider doing that we may postpone the deadline in a couple of weeks to mid may (but not guaranteed yet) - I'll hopefully update about that in a few days.

**Comment by limoneren** [comment]
That would be great, waiting for the final decision.:)

**Comment by dorarad** [comment]
Hi, alright good news we are going to extend the deadline to may 15. The evalAI server got updated and I will make a change in the formal website + notify by tomorrow. Best of luck! :)

**Comment by limoneren** [comment]
Thanks a lot for the update ! :)
