### ISSUE TITLE
‘official download page’ link encountered 404 error

### ISSUE THREAD

**Issue by orchardchang** [stanfordnlp/mac-network#25]
Hi 
‘official download page’ link encountered 404 error.
Plz check the website can work normally.

**Comment by dorarad** [comment]
hey, which link didn't work for you? could you please post it? there was a server error a couple of days ago but it has been resolved yesterday.
Is this work for you https://cs.stanford.edu/people/dorarad/gqa/download.html
?

**Comment by orchardchang** [comment]
@dorarad 
The link didn't work. https://github.com/stanfordnlp/mac-network/blob/gqa/visualreasoning.net/download.html 
The new provided link can work now.  Does "Download Questions" in the new link mean new version of GQA 1.1.2?

**Comment by dorarad** [comment]
Yea it is the most updated version. Will update github page to point the correct link as well.
The correct link is: visualreasoning.net/download.html (which points to https://cs.stanford.edu/people/dorarad/gqa/download.html)

**Comment by dorarad** [comment]
btw where did you see the link "https://github.com/stanfordnlp/mac-network/blob/gqa/visualreasoning.net/download.html" I can't find where in the repo I point to that address

**Comment by dorarad** [comment]
oh ok found it. Solved now!

**Comment by orchardchang** [comment]
Thanks for your help~
