### ISSUE TITLE
Is the question engine for gqa dataset available?

### ISSUE THREAD

**Issue by TheShadow29** [stanfordnlp/mac-network#27]
Hi. Thanks for the amazing repository. I was wondering if the question generation engine used to create the gqa dataset is available anywhere.

**Comment by dorarad** [comment]
Hi, no actually it's unfortunately not public. The main reason why I prefer to not make it available is that if I would it could potentially allow kind of "reverse engineering" of the questions to get around their natural-language-like aspects etc practically skipping some of the challenge of the dataset.

**Comment by alexgaskell10** [comment]
Hi @dorarad, I am wondering if you would consider releasing the question generation engine? It has been several years since this work was initially published and the challenge no longer seems to be ongoing. It would be great for the community if you could publish these, thanks!

**Comment by chenkq7** [comment]
Hi @dorarad, I am working on something like adding Intermediate results for each step in functional program in annotation. but i found not every functional step can be preformed on scene graph. for example, `choose younger`,(no relation about who is younger) `choose shorter`(no relation about who is shorter), `select person`(no annotation about an object is a person or not), or some annotation is just not so consistent, e.g. in functional program, operator `filter` with argument `playing baseball`, but the attr of the target person is `baseball`. i was wondering if the "functional program generation engine" is available? or if there is something like "answer engine" to verify the correctness of the functional program and can get the Intermediate results accordingly.

**Comment by Nacnano** [comment]
Hi @dorarad, I am working on generating the GQA Dataset for other languages. It would be nice if you can make the generation engine public. Thank you
