### ISSUE TITLE
About memory's variational dropout

### ISSUE THREAD

**Issue by dandelin** [stanfordnlp/mac-network#28]
First, thanks for sharing your great work.

As following your code, a question came across about your variational dropout on memory vector. (https://github.com/stanfordnlp/mac-network/blob/master/mac_cell.py#L215, https://github.com/stanfordnlp/mac-network/blob/master/mac_cell.py#L590)

It seems the mask is generated once when building graph, maintaining its shape afterwards (64, 512), and is applied always whether the model is in training or evaluation.

Since this kind of dropout produces stochastic result while evaluation, and accept only fixed batch size. I am wondering Is it ok to apply such method.

Correct me if I'm reading the code wrong.

**Comment by dorarad** [comment]
Hi, thank you for the interest in the repo!
Indeed, the mask is generated once and applied for all the cells. I noticed that doing so gives better performance than applying a randomly different mask after each cell, especially when there are many. Potentially the reason for that is that if you do a different mask after each cell overall there are very few continuous "gradient lines" from start to end that aren't masked by any of the steps, making training harder.

Please note that during evaluation all the dropouts in the model are always set to 1,
https://github.com/stanfordnlp/mac-network/blob/master/model.py#L122
and thus during evaluation there is no stochasticity. Only during training.

Please let me know if you have any other questions!

**Comment by dandelin** [comment]
Thank you for your kind and quick reply!

I must have misunderstood the code :(
So the memory dropout mask is created every batch iteration and maintaining its shape during the MACCell recurrence, and feed_dict at evaluation time creates the mask with prob=1. Am I right?

Thanks again and please close this issue if my recap is correct.

**Comment by dorarad** [comment]
No worries, what you described now is completely correct! :) 
happy to help!
