### ISSUE TITLE
Servers are not responding to download image features

### ISSUE THREAD

**Issue by limoneren** [stanfordnlp/mac-network#31]
Hi,

We needed to re-download all features from the given link in the readme. However, currently the servers are not responding both for objects and spatial features links (https://www.isitdownrightnow.com/nlp.stanford.edu.html). Is this a temporary outage?

**Comment by limoneren** [comment]
Looks like it is responding now. Closing the issue.

**Comment by dorarad** [comment]
Sometimes there might be a short outage but I may move the data to amazon
