### ISSUE TITLE
About "all_submission_data.json" file

### ISSUE THREAD

**Issue by mgunay15** [stanfordnlp/mac-network#32]
Hello,
When I try to run the command for submission, it cannot find "all_submission_data.json" file. I downloaded all the data from https://nlp.stanford.edu/data/gqa and I also could not find that file. Am I missing something?
Thanks,

**Comment by dorarad** [comment]
Hi! you can download it at https://nlp.stanford.edu/data/gqa/data1.2.zip.
It's the same as all_submission_questions.json in the gqa website but just in a list format which is what the code expects.
