### ISSUE TITLE
About object number

### ISSUE THREAD

**Issue by nlprmx** [stanfordnlp/mac-network#35]
Hi, 
I just processed the scene graph and the object feature, but I found that the number of objects in scenegraph.json is not equal to that in gqa_objects.h5 file. For example, the number of objects for image '2386621'  is 16 in train_sceneGraphs.json but is 18 in gqa_objects.h5 file.  Is there anything wrong with my processing?  And how to match the object number and the feature? 
Thanks!

**Comment by dorarad** [comment]
Hi, sorry for the delayed response things have been particularly busy recently! 

The difference between the json and the features is expected: while the objects in the json are the ground-truth objects (annotated by people) the object-based features are ones predicted automatically by a faster-rcnn object detector, and therefore they don't necessarily correspond to the ground-truth object annotations. 

I'm planning to release features for the ground-truth bounding boxes as well (such that they will correspond), as part of a new paper I was working on but that will probably take some time.. but will update when it's online!

**Comment by LMdeLiangMi** [comment]
Hi, @dorarad
So the features for up to 100 objects: (ImagesNum, 100, 2048) do not correspond to any object names and attributes? I remember that faster-rcnn would output the bbox and class of each object.
