### ISSUE TITLE
About the balanced dataset size

### ISSUE THREAD

**Issue by HoangAnhDoNguyen** [stanfordnlp/mac-network#38]
Hi,
I saw in the paper [https://cs.stanford.edu/people/dorarad/gqa/gqaPaper.pdf](url) that the balanced GQA dataset consists of 1.7M questions. However, when I download the dataset on [https://nlp.stanford.edu/data/gqa/questions1.2.zip](url) and count the number of samples. It's weird since I only found the balanced dataset with 1M samples. 
Thanks.

**Comment by dorarad** [comment]
Hi, sorry for the large delay missed this one! 
The questions in the updated version were regenerated compared to the first version that was reported in the paper - I made the balancing stronger which reduced the number of sampled in the balanced ver. Will be good to update the paper accordingly
In addition, note that the paper reports the overall number of questions in all splits training, dev, val and test
Hope it helps!
