### ISSUE TITLE
Scene graph

### ISSUE THREAD

**Issue by alibabadoufu** [stanfordnlp/mac-network#39]
Just wonder, does anyone has the scene graph for all splits of the GQA Dataset?

**Comment by dorarad** [comment]
No, the scene graphs of the test and dev sets are intentionally kept hidden so no one has access to them and they aren't being used for any baselines/models/features etc. 

The only place where they have been used was in an experiment on page 15 of the original GQA paper https://arxiv.org/pdf/1902.09506.pdf where I measured performance over "perfect sight" (blue column) to evaluate the importance of visual vs semantic/reasoning aspects of the dataset in terms of impact on accuracy of current models.
Hope it helps!
